FROM debian:9.2

RUN apt-get update && \
    apt-get upgrade -y && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y git \
    nano dos2unix debconf-utils && \
    echo mariadb-server mysql-server/root_password password vulnerables | debconf-set-selections && \
    echo mariadb-server mysql-server/root_password_again password vulnerables | debconf-set-selections && \
    DEBIAN_FRONTEND=noninteractive apt-get install -y \
    apache2 \
    mariadb-server \
    php \
    php-mysql \
    php-pgsql \
    php-pear \
    php-gd \
    && \apt-get clean \
    && rm -rf /var/lib/apt/lists/*

COPY php.ini /etc/php5/apache2/php.ini

RUN cd /tmp \
	&& git clone -b 2.0.1 --depth=1 https://github.com/digininja/DVWA.git \
	&& rm -r /var/www/html \
	&& mv -f DVWA/ /var/www/html/ 

COPY config.inc.php /var/www/html/config/

RUN chown www-data:www-data -R /var/www/html 

RUN service mysql start && \
    sleep 3 && \
    mysql -uroot -pvulnerables -e "CREATE USER app@localhost IDENTIFIED BY 'p@ss1234';CREATE DATABASE dvwa;GRANT ALL privileges ON dvwa.* TO 'app'@localhost;"

EXPOSE 80

COPY main.sh /
RUN dos2unix /main.sh
ENTRYPOINT ["/main.sh"]